name: Using snyk-scan to scan monorepos
on: push
jobs:
  Snyk-scan:
    runs-on: ubuntu-latest
    
#    strategy:
#      matrix:
#        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Install snyk-scan.sh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          sudo curl -LO  'https://raw.githubusercontent.com/snyk-tech-services/snyk-scan.sh/main/snyk-scan.sh'
          ls -l
          sudo chmod +x snyk-scan.sh
      - name: Run snyk-scan.sh for python
        run: |
          sudo ./snyk-scan.sh --mode=test --type=python
        continue-on-error: true
      - name: Run snyk-scan.sh for golang
        run: |
          sudo ./snyk-scan.sh --mode=test --type=golang
        continue-on-error: true
      - name: Run snyk-scan.sh for java_maven
        run: |
          sudo ./snyk-scan.sh --mode=test --type=java_maven
        continue-on-error: true
      - name: Run snyk-scan.sh for java_gradle
        run: |
          sudo ./snyk-scan.sh --mode=test --type=java_gradle
        continue-on-error: true
